### ISSUE TITLE
本站正在测试中

### ISSUE THREAD

**Issue by ZEROKISEKI** [ZEROKISEKI/sora3-comment-repo#1]
http://sora3.coding.me/2017/12/28/%E6%9C%AC%E7%AB%99%E6%AD%A3%E5%9C%A8%E6%B5%8B%E8%AF%95%E4%B8%AD/

**Comment by ZEROKISEKI** [comment]
测试评论和评论计数![:025:](http://sora3.coding.me/imgs/smilies/25.png)![:025:](http://sora3.coding.me/imgs/smilies/25.png)

**Comment by TranchBellic** [comment]
被震撼到了233![:008:](http://sora3.coding.me/imgs/smilies/8.png)
# 加油![:012:](http://sora3.coding.me/imgs/smilies/12.png)
![:025:](http://sora3.coding.me/imgs/smilies/25.png)

**Comment by xiexiaoge** [comment]
非常nice

**Comment by WonderSeven** [comment]
这个网站太漂亮了

**Comment by sogud** [comment]
![:012:](http://sora3.coding.me/imgs/smilies/12.png)![:012:](http://sora3.coding.me/imgs/smilies/12.png)帅气

**Comment by muyurainy** [comment]
被博主的主题惊艳到了，太赞了！

**Comment by RainorshineGW** [comment]
666
